apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-dance-templates
  description: A collection of RHDH templates for Project Dance
spec:
  type: url
  targets:
     - scaffolder-templates/quarkus-stssc-template/template.yaml
     - scaffolder-templates/register-component/template.yaml

